[tool.coverage.run]
source = ["battleship"]
omit = [
    "battleship/enums.py",
    "battleship/buffers/*",
    "battleship/view/*",
    "battleship/engine/game_constants.py",
    "battleship/__main__.py",
    "battleship/game_loop.py",
    "battleship/vk_provider.py",
    "setup.py"
]

[tool.black]
line-length=79
target-version = ["py37"]
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
# add for black compatible, more info: https://black.readthedocs.io/en/stable/the_black_code_style.html
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true