DEFAULT_FIELD_SIZE = (10, 10)
FOUR_DECK_COUNT = 1
THREE_DECK_COUNT = 2
TWO_DECK_COUNT = 3
SINGLE_DECK_COUNT = 4

SHOT_ATTEMPTS_COUNT = 1000
ATTEMPTS_PLACE_SHIP = 1000

GAME_SESSION_LENGTH = 3600
# GAME_SESSION_LENGTH = 36
