from pygame.rect import Rect

CELL_SIZE = 32

DEFAULT_CLIENT_SIZE = (CELL_SIZE * 27, CELL_SIZE * 14)
DEFAULT_GAME_FIELD_ELEMENT_SIZE = (CELL_SIZE * 10, CELL_SIZE * 10)
DEFAULT_WINDOW_SIZE = (CELL_SIZE * 27, CELL_SIZE * 14)
DEFAULT_MENU_COLLISION = Rect(
    0, 0, DEFAULT_WINDOW_SIZE[0], DEFAULT_WINDOW_SIZE[1]
)
DEFAULT_GAME_FIELD_ELEMENT_COLLISION = Rect(
    0,
    0,
    DEFAULT_GAME_FIELD_ELEMENT_SIZE[0],
    DEFAULT_GAME_FIELD_ELEMENT_SIZE[1],
)

INFO_TEXT = "Перейдите на сайт, " \
            "разрешите этому приложению делать посты, " \
            "скопируйте адресс сайта, " \
            "на который вас перенаправило и нажмите ЗДЕСЬ 'V'. " \
            "Далее подтвердите"

DEFAULT_TEXT_FILLCOLOR = (255, 116, 0)
WHITE_COLOR = (255, 255, 255)
RED_GREEN_COLOR = (255, 255, 0)
RED_BLUE_COLOR = (255, 0, 255)
RED_COLOR = (255, 0, 0)
GREEN_BLUE_COLOR = (0, 255, 255)
GREEN_COLOR = (0, 255, 0)
BLUE_COLOR = (0, 0, 255)
BLACK_COLOR = (0, 0, 0)
# DEFAULT_DISPLAY_COLOR = (30, 213, 200)
# DEFAULT_DISPLAY_COLOR = (234, 227, 211)
DEFAULT_DISPLAY_COLOR = (239, 222, 194)

DEAD_SHIP_PEACE = RED_COLOR
SHOT = GREEN_COLOR
EMPTY = (94, 242, 198)
WRONG_PEACE = RED_COLOR
SHIP_PEACE = BLUE_COLOR
FULL_DEAD_PEACE = BLACK_COLOR

LEFT_BUTTON_RECT = Rect(CELL_SIZE, CELL_SIZE, CELL_SIZE*10, CELL_SIZE*2)
RIGHT_BUTTON_RECT = Rect(CELL_SIZE*16, CELL_SIZE, CELL_SIZE*10, CELL_SIZE*2)
LEFT_LABEL_RECT = Rect(
    CELL_SIZE * 2,
    CELL_SIZE * 2 - round((CELL_SIZE * 2) / 3),
    CELL_SIZE*10,
    round((CELL_SIZE * 2) / 3)
)
RIGHT_LABEL_RECT = Rect(
    CELL_SIZE * 16,
    CELL_SIZE * 2 - round((CELL_SIZE * 2) / 3),
    CELL_SIZE * 10,
    round((CELL_SIZE * 2) / 3)
)
